import { css } from "@emotion/react";

export const container = css`width: min(100%, 1320px); margin: 0 auto; padding: 34px clamp(20px, 4vw, 56px) 56px;`;
export const mainBox = css`width: 100%;`;
export const filterBar = css`display:flex; flex-wrap:wrap; gap:8px; margin-bottom:30px;`;
export const filter = css`min-height:40px; padding:0 15px; border:1px solid var(--moa-line-strong); border-radius:11px; background:#fff; color:var(--moa-ink-subtle); font-weight:750; cursor:pointer;`;
export const activeFilter = css`${filter}; background:var(--moa-ink); color:#fff; border-color:var(--moa-ink);`;
export const sectionHeading = css`display:flex; align-items:center; justify-content:space-between; gap:16px; margin-bottom:16px; >h2{margin:0;font-size:22px;letter-spacing:-.03em;} >span{color:var(--moa-muted);font-size:13px;}`;
export const loadingBox = css`min-height:220px;display:grid;place-items:center;color:var(--moa-muted);background:var(--moa-surface-muted);border-radius:var(--moa-radius-lg);`;
export const selectCategry = css`display: flex; list-style: none; width: 150px; justify-content: space-around;`;
export const line = css`width: 100%; border-top: 1px solid var(--moa-line); margin: 10px 0;`;
export const groupList = css`display: grid; grid-template-columns: repeat(auto-fill, minmax(min(100%, 250px), 1fr)); gap: 18px; width: 100%; list-style: none; padding: 0; margin: 0;`;
export const groupLi = css`display:block;width:100%;padding:0 0 16px;border:1px solid var(--moa-line);border-radius:var(--moa-radius-md);overflow:hidden;background:var(--moa-surface);box-shadow:var(--moa-shadow-sm);transition:.18s ease;&:hover{transform:translateY(-3px);box-shadow:var(--moa-shadow-md);border-color:var(--moa-line-strong);}`;
export const listDetail = css`display:flex;align-items:flex-start;justify-content:space-between;gap:10px;padding:14px 15px 4px;>h3{margin:0;font-size:16px;line-height:1.45;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}`;
export const metaRow = css`display:flex;justify-content:space-between;gap:8px;padding:6px 15px 0;color:var(--moa-muted);font-size:12px;`;
export const categoryTag = css`position:absolute;left:12px;top:12px;padding:5px 9px;border-radius:8px;background:rgba(255,255,255,.92);color:var(--moa-ink);font-size:11px;font-weight:800;`;
export const content = css`margin: 0; color: var(--moa-ink); font-weight: 700;`;
export const marginPaddingDel = css`margin: 0; padding: 0 14px;`;
export const click = css`cursor: pointer; background: transparent; border: 0; color: var(--moa-primary);`;
export const imgDiv = css`position:relative;display:flex;align-items:center;width:100%;height:170px;overflow:hidden;cursor:pointer;border:0;padding:0;background:var(--moa-surface-muted);`;
export const img = css`width: 100%; height: 100%; object-fit: cover;`;
